// ABOUTME: Database helper functions for querying and managing notes in the Dexie database
// ABOUTME: Provides liveQuery for reactive note fetching and CRUD operations for note persistence

import Dexie from 'dexie';
import { db } from '$lib/db';
import type { NoteData } from '$lib/types/note';

const { liveQuery } = Dexie;

/**
 * Get all notes associated with a specific bookmark using liveQuery.
 * Returns a Dexie Observable that reactively updates when notes change.
 *
 * @param bookmarkId - The ID of the bookmark to fetch notes for
 * @returns Observable that emits NoteData[] sorted by created date (newest first)
 */
export function getBookmarkNotes(bookmarkId: string) {
	return liveQuery(async () => {
		const notes = await db.notes.where('bookmarks').equals(bookmarkId).toArray();

		// Sort by created date, newest first
		return notes.sort((a, b) => b.created.localeCompare(a.created));
	});
}

/**
 * Create a new note and associate it with a bookmark.
 * The note ID is auto-generated by Dexie.
 *
 * @param bookmarkId - The ID of the bookmark to associate the note with
 * @param text - The text content of the note
 * @returns Promise that resolves to the auto-generated note ID
 */
export async function createNote(bookmarkId: string, text: string): Promise<string> {
	const noteData: Omit<NoteData, 'id'> = {
		text,
		created: new Date().toISOString(),
		modified: null,
		bookmarks: [bookmarkId]
	};

	const id = await db.notes.add(noteData as NoteData);
	return id as string;
}

/**
 * Update an existing note's text content.
 * Sets the modified timestamp to the current time.
 *
 * @param noteId - The ID of the note to update
 * @param text - The new text content
 * @returns Promise that resolves when the update is complete
 */
export async function updateNote(noteId: string, text: string): Promise<void> {
	await db.notes.update(noteId, {
		text,
		modified: new Date().toISOString()
	});
}

/**
 * Delete a note from the database.
 *
 * @param noteId - The ID of the note to delete
 * @returns Promise that resolves when the deletion is complete
 */
export async function deleteNote(noteId: string): Promise<void> {
	await db.notes.delete(noteId);
}
